From ubuntu:16.04


# issue docker with -it -d to run in background

# Ensure that artifact is linked or imported into this folder for build
COPY fast-rtps/ /usr/local/
ENV LD_LIBRARY_PATH="/usr/local/lib"
CMD [ "/bin/bash" ]